name: ThinkBayes2

dependencies:
  - python>=3.6
  - jupyter
  - numpy
  - matplotlib
  - seaborn
  - pandas
  - statsmodels
  - lxml
  - html5lib
  - scipy
  - pymc3
  - pytables
  - pip
  - pip:
    - empiricaldist
